; ============================================================================
;  M5 PC Remote — M5StickC Plus2
;  Télécommande Bluetooth (clavier + touches multimédia) pour PC.
; ============================================================================

[env:m5stickc-plus2]
platform = espressif32
board = m5stick-c
framework = arduino

monitor_speed = 115200
monitor_filters = esp32_exception_decoder
upload_speed = 1500000

board_build.partitions = min_spiffs.csv

; USE_NIMBLE -> pile Bluetooth légère (moins de flash/RAM que Bluedroid)
build_flags =
    -D USE_NIMBLE
    -DCORE_DEBUG_LEVEL=0

lib_deps =
    m5stack/M5Unified @ ^0.2.0
    t-vk/ESP32 BLE Keyboard @ ^0.3.2
    h2zero/NimBLE-Arduino @ ^1.4.0
